// Emits packages/ui/theme.css from packages/ui/src/tokens.ts.
//
// Run via `pnpm --filter @kapa/ui build:theme`, which invokes this with
// `node --experimental-strip-types` — plain type-stripping, not a bundler,
// so this script (like tokens.ts) must import nothing beyond Node builtins.
//
// The generated file is committed. CI regenerates it and fails the build on
// any diff (see .github/workflows/ci.yml) — that's what makes it impossible
// to change a token and forget to update the CSS.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import {
  color,
  radius,
  shadow,
  font,
  fontSize,
  lineHeight,
  letterSpacing,
} from '../src/tokens.ts';

// sand500 -> sand-500, inkMuted -> ink-muted, accent -> accent
function kebab(key: string): string {
  return key
    .replace(/([0-9]+)/g, '-$1')
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .toLowerCase();
}

const lines: string[] = [];

function emitGroup(
  comment: string,
  prefix: string,
  values: Record<string, string | number>,
  unit = ''
) {
  lines.push(`  /* ${comment} */`);
  for (const [key, value] of Object.entries(values)) {
    lines.push(`  --${prefix}-${kebab(key)}: ${value}${unit};`);
  }
}

lines.push('  /* Font families — next/font (apps/web layout.tsx) loads the');
lines.push('     actual fonts and exposes them as these same CSS variables;');
lines.push("     this just gives Tailwind's font-body/font-heading utilities");
lines.push('     the fallback stack. */');
lines.push(`  --font-body: ${font.body};`);
lines.push(`  --font-heading: ${font.heading};`);
lines.push('');

emitGroup(
  'Secondary-text tones. Solid hexes, not opacity blends — opacity shifts\n' +
    "     toward whichever ground sits behind it, so its contrast ratio isn't\n" +
    '     fixed. ink-muted clears 4.5:1, ink-subtle is decorative-only —\n' +
    '     against both bg and surface.',
  'color',
  { bg: color.bg, surface: color.surface, ink: color.ink }
);
lines.push('');
emitGroup('Neutral / sand ramp', 'color', {
  inkMuted: color.inkMuted,
  inkSubtle: color.inkSubtle,
  sand100: color.sand100,
  sand200: color.sand200,
  sand300: color.sand300,
  sand400: color.sand400,
  sand500: color.sand500,
  sand600: color.sand600,
  sand700: color.sand700,
  sand800: color.sand800,
  sand900: color.sand900,
});
lines.push('');
emitGroup("Terracotta accent ramp (default = the design's #c67139)", 'color', {
  accent: color.accent,
  accent100: color.accent100,
  accent200: color.accent200,
  accent300: color.accent300,
  accent400: color.accent400,
  accent500: color.accent500,
  accent600: color.accent600,
  accent700: color.accent700,
  accent800: color.accent800,
  accent900: color.accent900,
});
lines.push('');
emitGroup('Sage "you\'re fine" ramp (default = #8fa073)', 'color', {
  sage: color.sage,
  sage100: color.sage100,
  sage200: color.sage200,
  sage300: color.sage300,
  sage400: color.sage400,
  sage500: color.sage500,
  sage600: color.sage600,
  sage700: color.sage700,
  sage800: color.sage800,
  sage900: color.sage900,
});
lines.push('');
emitGroup('White', 'color', { white: color.white });
lines.push('');

emitGroup('Corner radii', 'radius', radius, 'px');
lines.push('');

lines.push('  /* Shadows */');
for (const [key, value] of Object.entries(shadow)) {
  lines.push(`  --shadow-${kebab(key)}: ${value.css};`);
}
lines.push('');

lines.push(
  "  /* Type scale — additive, not an override of Tailwind's default text-*"
);
lines.push('     utilities. See tokens.ts for why these are index-keyed and');
lines.push('     namespaced under their own custom properties. */');
for (const [group, sizes] of Object.entries(fontSize)) {
  for (const [index, px] of Object.entries(sizes)) {
    lines.push(`  --text-${group}-${index}: ${px}px;`);
  }
}
lines.push('');
for (const [group, heights] of Object.entries(lineHeight)) {
  for (const [index, px] of Object.entries(heights)) {
    lines.push(`  --leading-${group}-${index}: ${px}px;`);
  }
}
lines.push('');
for (const [group, spacings] of Object.entries(letterSpacing)) {
  for (const [index, px] of Object.entries(spacings)) {
    lines.push(`  --tracking-${group}-${index}: ${px}px;`);
  }
}

const css = `/* GENERATED by packages/ui/scripts/build-theme.ts — do not edit.
   Source of truth: packages/ui/src/tokens.ts */
@theme {
${lines.join('\n')}
}
`;

const outPath = fileURLToPath(new URL('../theme.css', import.meta.url));
writeFileSync(outPath, css);
